"""questions: theme and abstract

Revision ID: 0119d406c1ad
Revises: 
Create Date: 2026-09-11 18:15:38.760662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0119d406c1ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('abstract', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_questions_theme'), ['theme'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_theme'))
        batch_op.drop_column('abstract')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
