"""questions: core_subject

Revision ID: 023a421901f6
Revises: 0119d406c1ad
Create Date: 2026-09-16 21:03:20.139707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023a421901f6'
down_revision: Union[str, Sequence[str], None] = '0119d406c1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('core_subject', sa.String(length=60), nullable=True))
        batch_op.create_index(batch_op.f('ix_questions_core_subject'), ['core_subject'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_core_subject'))
        batch_op.drop_column('core_subject')

    # ### end Alembic commands ###
