"""users.is_admin

Revision ID: 0852667df992
Revises: ca24bcac40e3
Create Date: 2026-09-18 17:50:43.537365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0852667df992'
down_revision: Union[str, Sequence[str], None] = 'ca24bcac40e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default, or the ALTER fails on any table that already has
        # rows: they need a value and NOT NULL leaves nowhere to get one
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False,
                                      server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
