"""llm jobs

Revision ID: 77af1d80be25
Revises: c5cbf92da5f8
Create Date: 2026-09-20 11:32:14.962040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77af1d80be25'
down_revision: Union[str, Sequence[str], None] = 'c5cbf92da5f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tache', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('chunk', sa.Integer(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('done_chunks', sa.Integer(), nullable=False),
    sa.Column('answered', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['review_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_jobs_status'))

    op.drop_table('llm_jobs')
    # ### end Alembic commands ###
