"""drop the questions table

Revision ID: 8eefb69d0194
Revises: effa028f1a69
Create Date: 2026-09-18 11:12:28.345385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eefb69d0194'
down_revision: Union[str, Sequence[str], None] = 'effa028f1a69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Drop `questions` - step 6 of "Core question set design.md".

    Everything it held now lives in the four-layer model:

        text, period, source, partie/sujet  ->  raw_questions (every sighting)
        the deduplicated question           ->  fingerprints
        occurrences                         ->  fingerprints.total_sightings
                                                list_questions.month_sightings
        theme / abstract / core_subject     ->  fingerprints, as foreign keys

    Nothing reads it: the API moved in step 4, `attempts` moved in step 5, and
    the labelling scripts were rewritten onto `fingerprints` (`seed.py` and
    `transfer_labels.py` deleted, superseded by `backfill_questions.py`).

    **This is the one destructive step in the plan.** The downgrade below
    recreates the schema but NOT the 2,861 rows, which cannot be rebuilt
    exactly - `seed.py`'s dedup rules are gone, and 45 of those rows held
    wording that predates the scraper fixes and no longer exists anywhere else.
    Nothing of value is lost (the labels are in `fingerprints` and their source
    JSONL files are on disk), but dump the table first if you want the option:

        DATABASE_URL=... .venv/bin/python -c "
        import json
        from sqlalchemy import text
        from app.db import engine
        with engine.connect() as c, open('questions_backup.jsonl','w') as fh:
            for r in c.execute(text('select * from questions')).mappings():
                fh.write(json.dumps(dict(r), ensure_ascii=False, default=str) + chr(10))"
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_core_subject'))
        batch_op.drop_index(batch_op.f('ix_questions_period'))
        batch_op.drop_index(batch_op.f('ix_questions_source'))
        batch_op.drop_index(batch_op.f('ix_questions_tache'))
        batch_op.drop_index(batch_op.f('ix_questions_tache_period'))
        batch_op.drop_index(batch_op.f('ix_questions_theme'))
        batch_op.drop_index(batch_op.f('ix_questions_year'))

    op.drop_table('questions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Recreate the table, empty. See the note in upgrade()."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('tache', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('source', sa.VARCHAR(length=32), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('period', sa.VARCHAR(length=7), nullable=False),
    sa.Column('partie', sa.INTEGER(), nullable=True),
    sa.Column('sujet', sa.INTEGER(), nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('occurrences', sa.INTEGER(), nullable=False),
    sa.Column('theme', sa.VARCHAR(length=40), nullable=True),
    sa.Column('abstract', sa.VARCHAR(length=200), nullable=True),
    sa.Column('core_subject', sa.VARCHAR(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_year'), ['year'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_theme'), ['theme'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_tache_period'), ['tache', 'period'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_tache'), ['tache'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_core_subject'), ['core_subject'], unique=False)

    # ### end Alembic commands ###
