"""job kind

Revision ID: b00fc58a8bc2
Revises: 77af1d80be25
Create Date: 2026-09-20 12:36:23.892027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00fc58a8bc2'
down_revision: Union[str, Sequence[str], None] = '77af1d80be25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=10), nullable=False,
                                      server_default='llm'))
        batch_op.create_index(batch_op.f('ix_llm_jobs_kind'), ['kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_jobs_kind'))
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
