"""review batches

Revision ID: c5cbf92da5f8
Revises: 0852667df992
Create Date: 2026-09-18 17:51:38.375709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5cbf92da5f8'
down_revision: Union[str, Sequence[str], None] = '0852667df992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('field', sa.String(length=20), nullable=False),
    sa.Column('tache', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_batches_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_batches_tache'), ['tache'], unique=False)

    op.create_table('review_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('f_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=200), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['review_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['f_id'], ['fingerprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_items_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_items_f_id'), ['f_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_items_f_id'))
        batch_op.drop_index(batch_op.f('ix_review_items_batch_id'))

    op.drop_table('review_items')
    with op.batch_alter_table('review_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_batches_tache'))
        batch_op.drop_index(batch_op.f('ix_review_batches_field'))

    op.drop_table('review_batches')
    # ### end Alembic commands ###
