"""list_questions

Revision ID: dbbf7179181c
Revises: e0dd5c5a1c06
Create Date: 2026-09-18 10:19:39.433222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbbf7179181c'
down_revision: Union[str, Sequence[str], None] = 'e0dd5c5a1c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_id', sa.Integer(), nullable=False),
    sa.Column('tache', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('month_sightings', sa.Integer(), nullable=False),
    sa.Column('representative_raw_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['f_id'], ['fingerprints.id'], ),
    sa.ForeignKeyConstraint(['representative_raw_id'], ['raw_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tache', 'period', 'f_id', name='uq_list_question_tache_period_f')
    )
    with op.batch_alter_table('list_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_list_questions_f_id'), ['f_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_list_questions_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_list_questions_tache'), ['tache'], unique=False)
        batch_op.create_index('ix_list_questions_tache_period', ['tache', 'period'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_list_questions_tache_period')
        batch_op.drop_index(batch_op.f('ix_list_questions_tache'))
        batch_op.drop_index(batch_op.f('ix_list_questions_period'))
        batch_op.drop_index(batch_op.f('ix_list_questions_f_id'))

    op.drop_table('list_questions')
    # ### end Alembic commands ###
