"""raw_questions, fingerprints, core_subjects, themes

Revision ID: e0dd5c5a1c06
Revises: 023a421901f6
Create Date: 2026-09-18 09:40:27.678995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0dd5c5a1c06'
down_revision: Union[str, Sequence[str], None] = '023a421901f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tache', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tache', 'name', name='uq_theme_tache_name')
    )
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_themes_tache'), ['tache'], unique=False)

    op.create_table('core_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_id', 'name', name='uq_core_subject_theme_name')
    )
    with op.batch_alter_table('core_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_core_subjects_theme_id'), ['theme_id'], unique=False)

    op.create_table('fingerprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('tache', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.Column('abstract', sa.String(length=200), nullable=True),
    sa.Column('core_subject_id', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.String(length=7), nullable=True),
    sa.Column('last_seen', sa.String(length=7), nullable=True),
    sa.Column('total_sightings', sa.Integer(), nullable=False),
    sa.Column('months_seen', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['core_subject_id'], ['core_subjects.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tache', 'fingerprint', name='uq_fingerprint_tache_hash')
    )
    with op.batch_alter_table('fingerprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fingerprints_core_subject_id'), ['core_subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fingerprints_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_fingerprints_tache'), ['tache'], unique=False)
        batch_op.create_index(batch_op.f('ix_fingerprints_theme_id'), ['theme_id'], unique=False)

    op.create_table('raw_questions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('f_id', sa.Integer(), nullable=False),
    sa.Column('tache', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('partie', sa.Integer(), nullable=True),
    sa.Column('sujet', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['f_id'], ['fingerprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_questions_f_id'), ['f_id'], unique=False)
        batch_op.create_index('ix_raw_questions_f_id_period', ['f_id', 'period'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_questions_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_questions_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_questions_tache'), ['tache'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_questions_tache'))
        batch_op.drop_index(batch_op.f('ix_raw_questions_source'))
        batch_op.drop_index(batch_op.f('ix_raw_questions_period'))
        batch_op.drop_index('ix_raw_questions_f_id_period')
        batch_op.drop_index(batch_op.f('ix_raw_questions_f_id'))

    op.drop_table('raw_questions')
    with op.batch_alter_table('fingerprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fingerprints_theme_id'))
        batch_op.drop_index(batch_op.f('ix_fingerprints_tache'))
        batch_op.drop_index(batch_op.f('ix_fingerprints_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_fingerprints_core_subject_id'))

    op.drop_table('fingerprints')
    with op.batch_alter_table('core_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_core_subjects_theme_id'))

    op.drop_table('core_subjects')
    with op.batch_alter_table('themes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_themes_tache'))

    op.drop_table('themes')
    # ### end Alembic commands ###
